### ISSUE TITLE
Does not play The Final Countdown by Europe when time is almost up

### ISSUE THREAD

**Issue by SteveDoesStuff** [adoxography/countdown#13]
For some reason the countdown timer is not playing Europe's hit song _The Final Countdown_ when there is only a few seconds left.

**To replicate**
1. Ensure computer volume is at 100%
1. Enter any amount of time and hit the play button to start the countdown
1. Wait for the timer to count down
1. Listen for Europe's _The Final Countdown_ to play as timer approaches 0

**Expected behaviour**
1. Chorus from _The Final Countdown_ by Europe plays as the countdown app approaches 0

**Comment by adoxography** [comment]
Thanks, now I'm going to have _The Final Countdown_ stuck in my head for the rest of the morning. Although this would be **amazing**, I have a sneaking suspicion Epic Records might have a differing opinion. 😢
